# Generated by Django 4.0.4 on 2022-12-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('idFornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
    ]
