# Generated by Django 4.0.4 on 2022-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(default='null', max_length=14),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='foto',
            field=models.CharField(default='null', max_length=9999),
        ),
    ]
