# Generated by Django 4.0.4 on 2022-12-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aprovacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovacoes',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='Pendente', max_length=20),
        ),
    ]
