# Generated by Django 4.0.4 on 2022-12-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fornecedores', '0002_fornecedores_cnpj_fornecedores_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('idPromocao', models.AutoField(primary_key=True, serialize=False)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('quantidadeVencedores', models.IntegerField()),
                ('maxCupomPessoa', models.IntegerField()),
                ('valorCupom', models.FloatField()),
                ('diasParaRecebimentoPremio', models.IntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Rascunho', 'Draft'), ('Aprovação Pendente', 'Aprovcaopendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Ativo', 'Ativo'), ('Finalizado', 'Finalizado')], default='Rascunho', max_length=20)),
                ('detalhesStatus', models.CharField(max_length=500)),
                ('premio', models.CharField(max_length=150)),
                ('idFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fornecedores.fornecedores')),
            ],
        ),
    ]
