# Generated by Django 4.0.4 on 2022-12-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Promocoes', '0002_alter_promocoes_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('endereco', models.CharField(max_length=500)),
                ('telefone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePromocao',
            fields=[
                ('idClientePromocao', models.AutoField(primary_key=True, serialize=False)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.clientes')),
                ('idPromocao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Promocoes.promocoes')),
            ],
        ),
    ]
