# Generated by Django 4.0.4 on 2022-12-12 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promocoes', '0002_alter_promocoes_status'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('idCupom', models.AutoField(primary_key=True, serialize=False)),
                ('numeroCupom', models.IntegerField()),
                ('dataDeCriacao', models.DateField()),
                ('status', models.CharField(choices=[('Valido', 'Valido'), ('Expirado', 'Expirado')], default='Valido', max_length=20)),
                ('sorteado', models.BooleanField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.clientes')),
                ('idPromocao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Promocoes.promocoes')),
            ],
        ),
    ]
